package tests;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;

public class OpenMainMenus {


    static String homeURL = "https://www.leadconsult.eu/";
    static String name = "John Doe";
    static String email = "john_doe@test.com";
    static String phone = "+359000000000";
    static String message = "This is a text generated by an automation software";
    static String expectedPageTitle;
    static String actualPageTitle;

    public static void main(String[] args)  {

        //System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver/linux_64/current");
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");
        options.addArguments("--start-maximized"); // open Browser in maximized mode
        options.addArguments("--disable-extensions"); // disabling extensions
        options.addArguments("--disable-infobars");
        options.addArguments("--remote-debugging-port=9222");
        options.setExperimentalOption("useAutomationExtension", false);
        options.addArguments("--remote-allow-origins=*");


        WebDriver driver = new ChromeDriver(options);

        WebDriverWait wait = new WebDriverWait(driver, 15);

        // Homepage:
        driver.get(homeURL);
        expectedPageTitle = "LEAD Consult - ETRM | Allegro | Energy Consulting";
        actualPageTitle = driver.getTitle();
        Assert.assertEquals(actualPageTitle, expectedPageTitle);

        //Services page:
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("menu-item-6363")));
        driver.findElement(By.id("menu-item-6363")).click();
        expectedPageTitle = "Services - LEAD Consult";
        actualPageTitle = driver.getTitle();
        Assert.assertEquals(actualPageTitle, expectedPageTitle);

        // Products page:
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("menu-item-7437")));
        driver.findElement(By.id("menu-item-7437")).click();
        expectedPageTitle = "Products - LEAD Consult";
        actualPageTitle = driver.getTitle();
        Assert.assertEquals(actualPageTitle, expectedPageTitle);

        // Customers page
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("menu-item-6620")));
        driver.findElement(By.id("menu-item-6620")).click();
        expectedPageTitle = "Customers - LEAD Consult";
        actualPageTitle = driver.getTitle();
        Assert.assertEquals(actualPageTitle, expectedPageTitle);

        // Careers page:
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("menu-item-6153")));
        driver.findElement(By.id("menu-item-6153")).click();
        expectedPageTitle = "Careers - LEAD Consult";
        actualPageTitle = driver.getTitle();
        Assert.assertEquals(actualPageTitle, expectedPageTitle);

        // Contact page:
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("menu-item-5819")));
        driver.findElement(By.id("menu-item-5819")).click(); // contact
        expectedPageTitle = "Contact us - LEAD Consult";
        actualPageTitle = driver.getTitle();
        Assert.assertEquals(actualPageTitle, expectedPageTitle);


        // Fill in name:
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\"wpcf7-f5661-p6126-o1\"]/form/p[1]/label/span/input")));
        driver.findElement(By.xpath("//*[@id=\"wpcf7-f5661-p6126-o1\"]/form/p[1]/label/span/input")).sendKeys(name); //fill in name

        // Fill in email:
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\"wpcf7-f5661-p6126-o1\"]/form/p[2]/label/span/input")));
        driver.findElement(By.xpath("//*[@id=\"wpcf7-f5661-p6126-o1\"]/form/p[2]/label/span/input")).sendKeys(email); //fill in email

        //Fill in phone:
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\"wpcf7-f5661-p6126-o1\"]/form/p[3]/label/span/input")));
        driver.findElement(By.xpath("//*[@id=\"wpcf7-f5661-p6126-o1\"]/form/p[3]/label/span/input")).sendKeys(phone); //fill in phone#

        // Fill in message:
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\"wpcf7-f5661-p6126-o1\"]/form/p[4]/label/span/textarea")));
        driver.findElement(By.xpath("//*[@id=\"wpcf7-f5661-p6126-o1\"]/form/p[4]/label/span/textarea")).sendKeys(message); //fill in message

        driver.close();
    }

}